FROM node:16

ENV HOST=0.0.0.0

WORKDIR /app

COPY public/ ./public/
COPY src/ ./src/
COPY babel.config.js .firebaserc package.json yarn.lock vue.config.js _redirects ./
RUN npm install bun -g
RUN bun install
EXPOSE 8080
CMD ["bun", "serve"]
