FROM node:16 AS base

ENV HOST=0.0.0.0

WORKDIR /app

COPY public/ ./public/
COPY src/ ./src/
COPY babel.config.js .firebaserc package.json yarn.lock vue.config.js _redirects ./

FROM base AS dev
RUN yarn install
EXPOSE 8080
CMD ["yarn", "serve"]
