FROM node:16

WORKDIR /src

RUN echo 'deb http://archive.debian.org/debian stretch main contrib non-free' | tee /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean;
RUN npm i -g firebase-tools
EXPOSE 9099
