FROM node:16 AS base
WORKDIR /app
ENV ETHERNAL_API_ROOT=
ENV NODE_ENV=production
ENV SECRET=
COPY pm2-server/package.json pm2-server/yarn.lock pm2-server/app.js pm2-server/index.js pm2-server/ecosystem.config.js ./
COPY pm2-server/lib/ ./lib
RUN yarn global add ethernal pm2
RUN pm2 install pm2-logrotate

FROM base AS dev
RUN yarn
CMD ["yarn", "run", "start:dev"]

FROM base AS prod
RUN yarn --prod
CMD ["yarn", "run", "start"]
