app = "ethernal-caddy"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.caddyfile"

# Caddy needs to see raw TLS handshake, so do NOT use handlers
[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80

[[services.tcp_checks]]
  interval = 10000
  timeout = 2000
  grace_period = "5s"
  restart_limit = 0

[[mounts]]
  source = "caddy_data"
  destination = "/data"
