# fly.toml app configuration file generated for ethernal-pm2 on 2023-08-11T11:17:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ethernal-pm2"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.pm2"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 200

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
