apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tasks
spec:
  template:
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: FIREBASE_CONFIG
          value: {"projectId": "ethernal-95a14"}